apiVersion: v1
kind: Service
metadata:
  labels:
    app: comet
  name: comet
spec:
  type: LoadBalancer
  ports:
  - name: "comet-http"
    port: 8000
    targetPort: 8000
  selector:
    app: comet
status:
  loadBalancer: {}
