apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: prowlarr
  name: prowlarr
spec:
  type: LoadBalancer
  ports:
  - name: "prowlarr-http"
    port: 9696
    targetPort: 9696
  selector:
    app: prowlarr
status:
  loadBalancer: {}
