apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config
      volumes:
      - name: prowlarr-config
        hostPath:
          path: /data/prowlarr/config
          type: Directory
