apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: jackett
  name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          image: lscr.io/linuxserver/jackett:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: AUTO_UPDATE
              value: "true"              
          volumeMounts:
            - mountPath: /config
              name: jackett-config
            - mountPath: /downloads
              name: jackett-downloads

      volumes:
      - name: jackett-config
        hostPath:
          path: /data/jackett/config
          type: Directory
      - name: jackett-downloads
        hostPath:
          path: /data/jackett/downloads
          type: Directory
