apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: jackett
  name: jackett
spec:
  type: LoadBalancer
  ports:
  - name: "jackett-http"
    port: 9117
    targetPort: 9117
  selector:
    app: jackett
status:
  loadBalancer: {}
